// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/whole-harvest-hero/Editorial.tsx": () => import("../components/mockups/whole-harvest-hero/Editorial.tsx"),
  "./components/mockups/whole-harvest-hero/ImpactLed.tsx": () => import("../components/mockups/whole-harvest-hero/ImpactLed.tsx"),
  "./components/mockups/whole-harvest-hero/Kinetic.tsx": () => import("../components/mockups/whole-harvest-hero/Kinetic.tsx")
};
